### ISSUE TITLE
ドキュメントの明文化

### ISSUE THREAD

**Issue by neet** [nakayosh/the-general#7]
レビュー負荷が高いっぽいので必要最低限のチェックポイントは予めCONTRIBUTING.mdだとかIssue template に書いて欲しい。

### 内容
- 開発環境のセットアップ
- 命名規則
- ディレクトリ構成
- チェックポイント（フォーマッタかけてるか、動作したかなど）

**Comment by chun37** [comment]
CONTRIBUTING.md, Issue Template, PullRequest Template の詳細を調べて、然るべき所に必要な情報が出るようにします。
